let
    Source = #"Cal EE Summary",
    #"Added Hourly Income" = Table.AddColumn(Source, "Hourly Income", each if [Hour Worked] = null or [Hour Worked] = 0 then null else [#"Medicare Taxable Wages - MCWG"] / [Hour Worked], type nullable number),
    #"Grouped Rows" = Table.Group(#"Added Hourly Income", {"Establishment", "CA Job Code", "CA Demo Code", "CA Pay Band Code", "Emp Status"}, {{"Number of EEs", each Table.RowCount(_), Int64.Type}, {"Worked Weeks.1", each List.Sum([Worked Weeks]), type number}, {"Hours Worked", each List.Sum([Hour Worked]), type number}, {"Med Taxable Wages", each List.Sum([#"Medicare Taxable Wages - MCWG"]), type nullable number}, {"Med Hourly Income", each List.Median(List.RemoveNulls([Hourly Income])), type nullable number}, {"Rows", each _, type table [Address Number=nullable number, Alpha Name=nullable text, Worked Weeks=number, Business Unit=nullable number, Business Unit_1=nullable text, Home Business Unit=nullable number, Home Business Unit_2=nullable text, #"Sex "=nullable text, EEO Job=nullable number, EEO Job_3=nullable text, EEO Min=nullable number, EEO Min_4=nullable text, F0116 ADDS=nullable text, Date Started=nullable date, #"Date Term."=nullable date, Pay Freq=nullable text, #"Medicare Taxable Wages - MCWG"=nullable number, Emp St=text, Emp Status=text, #"# Paychecks"=number, Total Hours=nullable number, CA Pay Band Code=number, CA Job Code=number, CA Demo Code=text, Hour Worked=number, Hourly Income=nullable number]}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Grouped Rows",{"Establishment", "CA Job Code", "CA Demo Code", "CA Pay Band Code", "Emp Status", "Number of EEs", "Hours Worked", "Worked Weeks.1"}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns", "Mean", each [Med Taxable Wages] / [Hours Worked]),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Med Taxable Wages", "Rows"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Mean", Currency.Type}, {"Med Hourly Income", Currency.Type}, {"Hours Worked", Int64.Type}, {"Worked Weeks.1", Int64.Type}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Changed Type",{"Establishment", "CA Job Code", "CA Demo Code", "CA Pay Band Code", "Emp Status", "Number of EEs", "Hours Worked", "Worked Weeks.1", "Mean", "Med Hourly Income"}),
    #"Added Custom1" = Table.AddColumn(#"Reordered Columns1", "Not Remote", each if [Establishment] = "Sales - CA" then null else [Number of EEs]),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Remote", each if [Not Remote] = null then [Number of EEs] else 0),
    #"Added Custom13" = Table.AddColumn(#"Added Custom2", "EmpType", each "Full-time"),
    #"Reordered Columns2" = Table.ReorderColumns(#"Added Custom13",{"Establishment", "CA Job Code", "CA Demo Code", "CA Pay Band Code", "Emp Status", "EmpType", "Number of EEs", "Hours Worked", "Worked Weeks.1", "Mean", "Med Hourly Income", "Not Remote", "Remote"}),
    #"Merged Queries" = Table.NestedJoin(#"Reordered Columns2", {"Establishment"}, Establishments, {"Establishment Name*"}, "Establishments", JoinKind.LeftOuter),
    #"Expanded Establishments" = Table.ExpandTableColumn(#"Merged Queries", "Establishments", {"Address Line 1*", "Address Line 2", "City*", "State*", "ZIP Code*", "NAICS Code*", "Major Activity*"}, {"Establishments.Address Line 1*", "Establishments.Address Line 2", "Establishments.City*", "Establishments.State*", "Establishments.ZIP Code*", "Establishments.NAICS Code*", "Establishments.Major Activity*"}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Expanded Establishments",{"Establishment", "Establishments.Address Line 1*", "Establishments.Address Line 2", "Establishments.City*", "Establishments.State*", "Establishments.ZIP Code*", "Establishments.NAICS Code*", "Establishments.Major Activity*", "CA Job Code", "CA Demo Code", "CA Pay Band Code", "Emp Status", "EmpType", "Number of EEs", "Hours Worked", "Worked Weeks.1", "Mean", "Med Hourly Income", "Not Remote", "Remote"}),
    #"Added Custom3" = Table.AddColumn(#"Reordered Columns3", "HQ", each "No"),
    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "Filed Last Year", each "Yes"),
    #"Establishment Totals" = Table.Group(#"Added Custom4", {"Establishment"}, {{"Establishment Total", each List.Sum([Number of EEs]), Int64.Type}}),
    #"Merged Establishment Totals" = Table.NestedJoin(#"Added Custom4", {"Establishment"}, #"Establishment Totals", {"Establishment"}, "EstablishmentTotals", JoinKind.LeftOuter),
    #"Expanded Establishment Totals" = Table.ExpandTableColumn(#"Merged Establishment Totals", "EstablishmentTotals", {"Establishment Total"}, {"Establishment Total"}),
    #"Reordered Columns4" = Table.ReorderColumns(#"Expanded Establishment Totals",{"Establishment", "Establishments.Address Line 1*", "Establishments.Address Line 2", "Establishments.City*", "Establishments.State*", "Establishments.ZIP Code*", "Establishments.NAICS Code*", "Establishments.Major Activity*", "HQ", "Filed Last Year", "Establishment Total", "CA Job Code", "CA Demo Code", "CA Pay Band Code", "Emp Status", "EmpType", "Number of EEs", "Hours Worked", "Worked Weeks.1", "Mean", "Med Hourly Income", "Not Remote", "Remote"})
in
    #"Reordered Columns4"